### ISSUE TITLE
es6 files with `truffle exec` no longer work.

### ISSUE THREAD

**Issue by tcoulter** [ConsenSys/truffle#106]

**Comment by tcoulter** [comment]
On master.

**Comment by simondlr** [comment]
I pulled all the latest code (in development). Can't do any truffle commands. eg

```
Simons-MacBook-Pro:Token-Factory simondlr$ truffle serve
/usr/local/lib/node_modules/truffle/lib/init.js:5
  all(config, callback) {
     ^
SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/truffle/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/index.js:2:9)
    at Module._compile (module.js:460:26)
```

I assume this has to do with all the es6 code being ported over to js? This seems like the right spot to put this, since it seesm related.

**Comment by simondlr** [comment]
nvm. I was using an old node version.

**Comment by tcoulter** [comment]
This should be fixed on master.
