### ISSUE TITLE
Truffle 1.0.1 fails a test after fresh `truffle init`

### ISSUE THREAD

**Issue by flyswatter** [ConsenSys/truffle#133]
```
➜  dancoin truffle test
Using environment test.
Compiling contracts...


  Contract: MetaCoin
    ✓ should put 10000 MetaCoin in the first account (45ms)
    1) should call a function that depends on a linked library
    > No events were emitted
    ✓ should send coin correctly (156ms)


  2 passing (1s)
  1 failing

  1) Contract: MetaCoin should call a function that depends on a linked library  :
     Error: Error: VM Exception while executing eth_call: invalid JUMP
    at /Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:122:17
    at /Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:55:5
    at /Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:726:13
    at /Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:52:16
    at /Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:269:32
    at /Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:44:16
    at /Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:723:17
    at /Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:167:37
    at /Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:51:9
    at /Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/cache.js:106:7
      at Object.module.exports.InvalidResponse (/Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/truffle/node_modules/web3/lib/web3/errors.js:35:16)
      at /Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/truffle/node_modules/web3/lib/web3/requestmanager.js:86:36
      at [object Object].request.onreadystatechange (/Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:114:13)
      at [object Object].dispatchEvent (/Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/truffle/node_modules/web3/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (/Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/truffle/node_modules/web3/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (/Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/truffle/node_modules/web3/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at endReadableNT (_stream_readable.js:905:12)
      at Function.module.exports.loopWhile (/Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/truffle/node_modules/deasync/index.js:64:21)
      at /Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/truffle/node_modules/deasync/index.js:36:18
      at runTask (/Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/truffle/cli.js:46:12)
      at Object.<anonymous> (/Users/danfinlay/.nvm/versions/node/v4.3.1/lib/node_modules/truffle/cli.js:331:14)
      at node.js:962:3
```

Ninja edit: Didn't have testrpc running, pasted wrong output.

**Comment by flyswatter** [comment]
Upon updating `testrpc` to the latest version this worked again.  This is almost definitely the new homestead features.
