### ISSUE TITLE
Compilation problems when using "import as" syntax

### ISSUE THREAD

**Issue by Latrasis** [ConsenSys/truffle#148]
Seems that truffle breaks on using solidity `import "foo.sol" as foo` syntax.

```
TypeError: Cannot read property 'source' of undefined
    at include_source_for (/Users/latrasis/.nvm/versions/node/v5.10.1/lib/node_modules/truffle/lib/contracts.js:90:77)
    at walk_down (/Users/latrasis/.nvm/versions/node/v5.10.1/lib/node_modules/truffle/lib/contracts.js:108:9)
    at Array.forEach (native)
    at walk_from (/Users/latrasis/.nvm/versions/node/v5.10.1/lib/node_modules/truffle/lib/contracts.js:139:24)
    at Array.forEach (native)
    at /Users/latrasis/.nvm/versions/node/v5.10.1/lib/node_modules/truffle/lib/contracts.js:143:28
    at /Users/latrasis/.nvm/versions/node/v5.10.1/lib/node_modules/truffle/node_modules/async/lib/async.js:52:16
    at done (/Users/latrasis/.nvm/versions/node/v5.10.1/lib/node_modules/truffle/node_modules/async/lib/async.js:246:17)
    at /Users/latrasis/.nvm/versions/node/v5.10.1/lib/node_modules/truffle/node_modules/async/lib/async.js:44:16
    at /Users/latrasis/.nvm/versions/node/v5.10.1/lib/node_modules/truffle/lib/contracts.js:49:9
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
    at Function.module.exports.loopWhile (/Users/latrasis/.nvm/versions/node/v5.10.1/lib/node_modules/truffle/node_modules/deasync/index.js:72:22)
    at /Users/latrasis/.nvm/versions/node/v5.10.1/lib/node_modules/truffle/node_modules/deasync/index.js:44:19
    at runTask (/Users/latrasis/.nvm/versions/node/v5.10.1/lib/node_modules/truffle/cli.js:46:12)
    at Object.<anonymous> (/Users/latrasis/.nvm/versions/node/v5.10.1/lib/node_modules/truffle/cli.js:331:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

```

**Comment by tcoulter** [comment]
Hi there. I believe this has been fixed in solidity-parser, a module Truffle uses. Please reopen this ticket if you're still having an issue. Thanks for reporting!
