### ISSUE TITLE
Compile issue: TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by shayanb** [ConsenSys/truffle#193]
Compiling was working until some major changes I did and added some contracts to my main contract, even though my linter doesnt show any errors, truffle fails to compile. but the error message is not really clear what is wrong here.

```
truffle compile
Checking sources...
TypeError: Cannot read property 'source' of undefined
    at include_source_for (/usr/local/lib/node_modules/truffle/lib/contracts.js:89:77)
    at walk_down (/usr/local/lib/node_modules/truffle/lib/contracts.js:107:9)
    at Array.forEach (native)
    at walk_from (/usr/local/lib/node_modules/truffle/lib/contracts.js:138:24)
    at Array.forEach (native)
    at /usr/local/lib/node_modules/truffle/lib/contracts.js:142:28
    at /usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:246:17)
    at /usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/truffle/lib/contracts.js:49:9
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
    at Function.module.exports.loopWhile (/usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:72:22)
    at /usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:44:19
    at runTask (/usr/local/lib/node_modules/truffle/cli.js:46:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/cli.js:331:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

**Comment by raineorshine** [comment]
Make sure that your contracts are all listed correctly by name in `truffle.js` in the contracts section.

**Comment by shayanb** [comment]
They are all listed there, it might have something to do with `oraclizeAPI.sol`

**Comment by prashantpawar** [comment]
Same problem, oraclizeAPI.sol included too

**Comment by shayanb** [comment]
@prashantpawar I bypassed that error by changing `oraclizeAPI.sol` file name to `usingOraclize.sol` and it seems to be working now. I'll update it when I'm done testing.

this error message gave me the hint that truffle is looking for a contract with the same name as the file name
```
Compiling oraclizeAPI.sol...
Error compiling:

Could not find expected contract or library in 'oraclizeAPI.sol': contract or library 'oraclizeAPI' not found.
Compiliation failed. See above.
```

**Comment by tcoulter** [comment]
> this error message gave me the hint that truffle is looking for a contract with the same name as the file name

Ya, that's a requirement of Truffle. I want to remove that requirement. Removing that requirement is implicit in #204. Thank you for trudging through this. I'm going to close this ticket and add this requirement be removed in #204.
