### ISSUE TITLE
[Error] truffle fails to build project consisting of only a contract and a test file

### ISSUE THREAD

**Issue by SethVgr** [ConsenSys/truffle#222]
# Checklist
- [done ] installed **truffle** and **testrpc**

```
# npm install -g truffle
# npm install -g testrpc
```

Created a directory and ran initialized truffle:

```
mkdir test_project
cd test_project
truffle init
```

Cleared the pregenerated contracts and tests:

`rm -r tests/* contracts/* build/*`

Added a minimalist contract and test js file:

**C.sol**
```
contract C {
    
    string words = "Bla bla bla";
    
    uint256 lastVal;
    
    function math(uint256 a, uint256 b) returns (uint256) {
        lastVal = a + b;
        return lastVal;
    }
    
    function getWords() constant returns (string) {
        return words;
    }
}
```

**c.js**
```
contract('C', function(accounts) {
  it("Getting the words string from the contract", function() {
    var c = C.deployed();

    return c.getWords.call(accounts[0]).then(function(words) {
      assert.equal(words, "Bla bla bla", "[E] The contract should have said \"Bla bla bla\"");
    });
  });

  it(" 2 + 2 = 4 ", function(){
    var c = C.deployed();

    return c.math(2, 2).then(function(additionResult){
        assert.equal(additionResult, 4, "[E] 2 + 2 = 4 even in eth. contracts.");
    });
  });
});
```

and ran 

`truffle build`

## System/environment

- OS: debian 8.3 Jessie x64, kernel version 3.16.0-4-amd64, virtual machine, running on VirtualBox, host machine Win7 x64, NAT network settings used

## Expected behaviour

**truffle** should have generated build artifacts in the build directory but it didn't (the directory is empty).

## Observed behaviour

There are no files added to the **build** directory.

**Comment by tcoulter** [comment]
You need to run `truffle compile` or `truffle migrate` for these artifacts to be generated. Did you run either of these commands after deleting the `build` directory? The reason `truffle build` doesn't generate these artifacts is that it's assumed you'll want to at least compile your contracts before building your frontend. We can add compilation as a dependency, however.

That said, if you *only* have a test and a solidity file, you wouldn't want to run `truffle build` anyway. I understand however that in other frameworks, `build` is synonymous with `compile`, so perhaps we should merge the two.

**Comment by SethVgr** [comment]
I have managed to build the contract (I ran `truffle compile`) but am still not able to launch the test cases. Can truffle launch test cases automatically?

**Comment by tcoulter** [comment]
You can launch the tests by running `truffle test`. Truffle will also recompile and migrate for you in this case. 

You can use `truffle compile`/`test`/`migrate` without any requirement on the frontend code. If you don't want to deal with the frontend code, just remove the `app` directory, remove the `build` configuration from `truffle.js`, and don't call `truffle build` or `truffle serve`. 

I'm going to close this for housekeeping purposes. Please let m know if you have another issue.

**Comment by Akshay-agarwal** [comment]
When i run truffle Migrate i am getting an error. I am not understanding this 

Error: Invalid JSON RPC response: "Error: connect ECONNREFUSED 127.0.0.1:8545\n    at Object.exports._errnoException (util.js:1026:11)\n    at exports._exceptionWithHostPort (util.js:1049:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)"
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/errors.js:35:16)
    at request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:111:32)
    at dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at handleError (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:532:5)
    at ClientRequest.errorHandler (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by tcoulter** [comment]
@Akshay-agarwal That means Truffle couldn't connect to your Ethereum client. You need to have an Ethereum client running. Please take a look at the documentation: http://truffle.readthedocs.io/en/latest/getting_started/client/

**Comment by Shubhajit1997** [comment]
when I write truffle compile/migrate/test I am having this error: 


Compiling your contracts...
===========================
C:\Users\user\.config\truffle\compilers\node_modules\soljson-v0.5.12+commit.7709ece9.js:16
function N7a(a,c,d,e,g,h){a=a|0;c=c|0;d=d|0;e=e|0;g=g|0;h=h|0;var i=0,j=0,k=0,l=0,m=0,n=0,o=0,p=0,q=0,r=0,s=0,u=0,w=0,x=0,y=0,z=0,A=0,B=0,C=0,D=0,E=0,F=0,G=0,H=0,I=0,J=0,K=0,L=0,M=0,N=0,O=0,P=0,Q=0,R=0,S=0,T=0,U=0,V=0,W=0,X=0,Y=0,Z=0,_=0,$=0,aa=0,ca=0,da=0,ea=0,ga=0,ia=0,ja=0,ka=0,la=0,ma=0,na=0,oa=0,pa=0,qa=0,ra=0,ta=0,wa=0,xa=0,ya=0,za=0,Aa=0,Ba=0,Ca=0,Da=0,Ea=0,Fa=0,Ga=0,Ha=0,Ia=0,Ja=0,Ka=0,La=0,Ma=0,Na=0,Oa=0,Pa=0,Qa=0,Ra=0,Sa=0,Ta=0,Ua=0,Va=0,Wa=0,Xa=0,Ya=0,Za=0,_a=0,$a=0,ab=0,bb=0,cb=0,db=0,eb=0,fb=0,gb=0,hb=0,ib=0,jb=0,kb=0,lb=0,mb=0,nb=0,ob=0,pb=0,qb=0,rb=0,sb=0,tb=0,wb=0,xb=0,yb=0,zb=0,Ab=0,Bb=0,Cb=0,Db=0,Eb=0,Fb=0,Hb=0,Ib=0,Jb=0,Kb=0,Lb=0,Mb=0,Nb=0,Ob=0,Pb=0,Qb=0,Rb=0,Sb=0,Tb=0,Ub=0,Vb=0,Wb=0,Xb=0,Yb=0,Zb=0,_b=0,$b=0,ac=0,bc=0,cc=0,dc=0,ec=0,fc=0,gc=0,hc=0,ic=0,jc=0,kc=0,lc=0,mc=0,nc=0,oc=0,pc=0,qc=0,rc=0,sc=0,tc=0,uc=0,vc=0,wc=0,xc=0,zc=0,Ac=0,Bc=0,Cc=0,Dc=0,Ec=0,Fc=0,Gc=0,Hc=0,Ic=0,Jc=0,Kc=0,Lc=0,Mc=0,Nc=0

SyntaxError: Unexpected end of input
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at VersionRange.getCachedSolcByFileName (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-solidity\compilerSupplier\loadingStrategies\VersionRange.js:36:1)
    at VersionRange.getCachedSolcByVersionRange (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-solidity\compilerSupplier\loadingStrategies\VersionRange.js:55:1)
    at VersionRange.load (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-solidity\compilerSupplier\loadingStrategies\VersionRange.js:194:1)
    at C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-solidity\compilerSupplier\index.js:71:1
    at new Promise (<anonymous>)
    at CompilerSupplier.load (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-solidity\compilerSupplier\index.js:51:1)
    at C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-solidity\profiler\index.js:98:1
Truffle v5.1.7 (core: 5.1.7)
Node v12.13.0
