### ISSUE TITLE
Error when building thru webpack

### ISSUE THREAD

**Issue by chevdor** [ConsenSys/truffle#287]
## Issue

Error when building thru webpack.

## Steps to Reproduce

I followed the doc. The issue occurs at `npm run dev``

## Expected Behavior

No error

## Actual Results

I added a bit of output to understand (long paths have been truncated):

```
ERROR in ./src/contracts/Contract.sol.js
Module build failed: Error: Could not find built Migrations contract. Error is {"errno":-2,"code":"ENOENT","syscall":"open","path":"/var/folders/ff/pqx4w8zx5yd73j2vq4004r4c0000gn/T/webpack-truffle11694-33621-1ercxkh.s3te78ehfr/Migrations.sol.js"} migrations_contract=/var/folders/ff/pqx4w8zx5yd73j2vq4004r4c0000gn/T/webpack-truffle11694-33621-1ercxkh.s3te78ehfr/Migrations.sol.js
    at /Users/..../node_modules/truffle/lib/migrate.js:216:32
    at ReadFileContext.callback (/Users/.../node_modules/ether-pudding/index.js:214:23)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
 @ ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Contract.vue 15:25-70

```

As mentioned in the doc, I did add the following entry to truffle.js
`migrations_directory: "./migrations"`

From truffle.js, the migration path "./migrations" is correct and the folder does contain my migration scripts.

## Environment

* Operating System: OSX
* Truffle version: The local version is truffle@2.0.8. Global version as well
* Ethereum client: testrpc
* node version: 6.7.0
* npm version: 3.10.7

**Comment by chevdor** [comment]
My contracts folder contained the .sol.js files and was missing the .sol files
Adding the .sol files to that folder fixed the issue.
