### ISSUE TITLE
Truffle console fails with an unreadable error when no rpc is running

### ISSUE THREAD

**Issue by LogvinovLeon** [ConsenSys/truffle#337]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When `testrpc` is not running `truffle console` fails with an unreadable error message.

## Steps to Reproduce

Run `travis console` without `testrpc`

## Expected Behavior

Human readable error, which suggests, that an RPC is unreachable.

## Actual Results

```
truffle console
/usr/local/lib/node_modules/truffle/lib/repl.js:25
    if (err) return done(err);
                    ^

ReferenceError: done is not defined
    at /usr/local/lib/node_modules/truffle/lib/repl.js:25:21
    at /usr/local/lib/node_modules/truffle/lib/repl.js:57:21
    at /usr/local/lib/node_modules/truffle/lib/contracts.js:46:25
    at /usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/property.js:119:13
    at /usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/requestmanager.js:82:20
    at exports.XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:114:13)
    at exports.XMLHttpRequest.dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at exports.XMLHttpRequest.handleError (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:532:5)
    at ClientRequest.errorHandler (/usr/local/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
```

## Environment

* Operating System: MacOS
* Truffle version: Truffle v2.1.1
* Ethereum client: No
* node version: v7.2.0
* npm version: 3.10.9

**Comment by tcoulter** [comment]
This is no longer the case on master. The current error is `Error: Invalid JSON RPC response: ""`, which is still cryptic, but at least that's standard across Truffle. A new issue should be added that when a provider is required that it checks the connection first by calling a standard request (`eth_version` or something) and produces a human readable error if that fails. Would love for you to write that issue if you feel it's a problem.

Thanks for submitting!
