### ISSUE TITLE
Fatal error: Invalid array length

### ISSUE THREAD

**Issue by tymat** [ConsenSys/truffle#4]
We're getting a fatal error during ```truffle deploy```.  

Please see below.

**Output**

```shell
$ truffle deploy
Using environment development.
Compiling GoldRegistry.sol...
Sending GoldRegistry.sol to the network...
Verifying deployment...
Fatal error: Invalid array length
```

**Contract**

```javascript
contract GoldRegistry {
    address public ca;

    mapping (address => bool) public bars;

    modifier onlyca { if (msg.sender == ca) _ }

    function GoldRegistry() {
        ca = msg.sender;
    }

    function registerGold(address goldid) onlyca {
        bars[goldid] = true;
    }
}
```

**config.json**

```javascript
{
  "frontend": {
    // Copy ./app/index.html (right hand side) to ./build/index.html.
    "index.html": "index.html",
    "app.js": [
      // Paths relative to "app" directory that should be
      // concatenated and processed during build.
      "javascripts/app.coffee" 
    ],
    "app.css": [
      // Paths relative to "app" directory that should be
      // concatenated and processed during build.
      "stylesheets/app.scss"
    ],
    // Note: You can also include directories.
    // This will copy a static images directory to the build directory.
    "images/": "images/"
  },
  "deploy": [
    // Names of contracts that should be deployed to the network.
    "GoldRegistry"
  ],
  "rpc": {
    // Default RPC configuration.
    "host": "jonsix",
    "port": 8080
  }
}
```

**Project contents**
```
$ tree
.
├── app
│   ├── images
│   ├── index.html
│   ├── javascripts
│   │   └── app.coffee
│   └── stylesheets
│       └── app.scss
├── config
│   ├── app.json
│   ├── development
│   │   ├── config.json
│   │   └── contracts.json
│   ├── production
│   │   ├── config.json
│   │   └── contracts.json
│   ├── staging
│   │   ├── config.json
│   │   └── contracts.json
│   └── test
│       ├── config.json
│       └── contracts.json
├── contracts
│   └── GoldRegistry.sol
└── test
    └── goldregistry.coffe
```

**solc compilation**
```
$ solc --binary stdout
contract GoldRegistry {
    address public ca;

    mapping (address => bool) public bars;

    modifier onlyca { if (msg.sender == ca) _ }

    function GoldRegistry() {
        ca = msg.sender;
    }

    function registerGold(address goldid) onlyca {
        bars[goldid] = true;
    }
}
^D
======= GoldRegistry =======
Binary:
60606040525b33600060006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908302179055505b6101a9806100406000396000f30060606040526000357c01000000000000000000000000000000000000000000000000000000009004806313e8e8e11461004f5780637934fd9614610062578063b3c0960f146100995761004d565b005b61006060048035906020015061010b565b005b61006d6004506100c0565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b6100aa6004803590602001506100e6565b6040518082815260200191505060405180910390f35b600060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600160005060205280600052604060002060009150909054906101000a900460ff1681565b600060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614156101a5576001600160005060008373ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff021916908302179055505b5b5056
```

**Environment**
```
Geth/v0.9.35/freebsd/go1.4.2
```

**Comment by tcoulter** [comment]
Thanks for all the info @tymat! Looking.

**Comment by tymat** [comment]
Here's the output of --verbose-rpc

https://gist.github.com/tymat/285a32c6f0b298ec00f6

**Comment by tcoulter** [comment]
@tymat Can you run `truffle deploy --stack`?

**Comment by tymat** [comment]
```
$ truffle deploy --stack
Using environment development.
Compiling GoldRegistry.sol...
Sending GoldRegistry.sol to the network...
Verifying deployment...
Fatal error: Invalid array length
RangeError: Invalid array length
  at padLeft (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/utils/utils.js:75:12)
  at toAddress (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/utils/utils.js:384:19)
  at /usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/method.js:85:28
  at Array.map (native)
  at [object Object].Method.formatInput (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/method.js:84:32)
  at [object Object].Method.toPayload (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/method.js:130:23)
  at [object Object].Method.send (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/method.js:161:24)
  at [object Object].verify (/usr/local/lib/node_modules/truffle/lib/contracts.coffee:121:25)
  at [object Object].wrapper [as _onTimeout] (timers.js:265:14)
  at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by tcoulter** [comment]
Hmm. This appears to be an issue with web3. Can you run this in the command line:

```
cd $(npm config --global get prefix)/lib/node_modules/truffle/ 
npm list web3
```

**Comment by tymat** [comment]
```
truffle@0.0.6 /usr/local/lib/node_modules/truffle
└── web3@0.7.1
```

It seems like geth 0.9.35 changed the return for sendTransaction.  

This might be our culprit:  https://github.com/ethereum/go-ethereum/issues/1422

**Comment by tymat** [comment]
You now have to do the following to get the address of the new contract:

```
> eth.getTransactionReceipt('0x4091220df42ba127ee81650671ea0bd1ef716d4ad988e88c41d1147abcf4de04')
{
  blockHash: '0xc4381cd143999b45cae5bbff91f9f41aaf01f120935722fc84464d9caf2aa2c4',
  blockNumber: 889,
  contractAddress: '0x496bcf0785aa7eb31facbe64316a91cef6350fc6',
  cumulativeGasUsed: 155507,
  gasUsed: 3141592,
  logs: [ ],
  transactionHash: '0x4091220df42ba127ee81650671ea0bd1ef716d4ad988e88c41d1147abcf4de04',
  transactionIndex: 0
```

**Comment by tcoulter** [comment]
Yep, that looks like the culprit. Will leave this open to figure out what to do next (I'm assuming the other clients will come around). In the meantime, may I recommend the TestRPC? https://github.com/ConsenSys/testrpc

**Comment by tymat** [comment]
It seems like web3 has getTransactionReceipt()  

```
web3.eth.getTransactionReceipt('0x4091220df42ba127ee81650671ea0bd1ef716d4ad988e88c41d1147abcf4de04')
{ transactionHash: '0x4091220df42ba127ee81650671ea0bd1ef716d4ad988e88c41d1147abcf4de04',
  transactionIndex: 0,
  blockNumber: 889,
  blockHash: '0xc4381cd143999b45cae5bbff91f9f41aaf01f120935722fc84464d9caf2aa2c4',
  cumulativeGasUsed: 155507,
  gasUsed: 3141592,
  contractAddress: '0x496bcf0785aa7eb31facbe64316a91cef6350fc6',
  logs: [] }
>
```

@obscuren says it's intentional.  I'm going to ask @debris what they are doing.

**Comment by tcoulter** [comment]
Oh interesting. I didn't see it in the docs. In that case, I'll see if I can conditionally support both.

**Comment by tcoulter** [comment]
@tymat Update truffle via npm. It should fix your issue. Let me know if you run into anything else.

**Comment by tymat** [comment]
Thanks.  It works now.
