### ISSUE TITLE
Can't run truffle init

### ISSUE THREAD

**Issue by alper** [ConsenSys/truffle#45]
I installed as per the instructions and I try to run truffle init and I get.

```
Error: Source directory undefined doesn't exist!
  at module.exports.load (/usr/local/lib/node_modules/truffle/node_modules/ether-pudding/loader.js:8:13)
  at /usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:35:6
  at Object.gather (/usr/local/lib/node_modules/truffle/lib/config.es6:332:17)
  at /usr/local/lib/node_modules/truffle/truffle.es6:150:23
  at /usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:35:6
  at runTask (/usr/local/lib/node_modules/truffle/truffle.es6:55:5)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/truffle.es6:345:14)
  at Module._compile (module.js:435:26)
  at normalLoader (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6] (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/babel/lib/_babel-node.js:144:25)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3
```

**Comment by tcoulter** [comment]
Hi there. Yep, this has already been brought to my attention. Will have a patch soon.

**Comment by tcoulter** [comment]
Fixed. Reinstall, you should now have version 0.2.2.
