### ISSUE TITLE
truffle init - Error: Source directory undefined doesn't exist!

### ISSUE THREAD

**Issue by ramvi** [ConsenSys/truffle#46]
I am stopped by an error right away. I installed truffle, then:
```
$ truffle 
Error: Source directory undefined doesn't exist!
  at module.exports.load (/usr/local/lib/node_modules/truffle/node_modules/ether-pudding/loader.js:8:13)
  at /usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:35:6
  at Object.gather (/usr/local/lib/node_modules/truffle/lib/config.es6:332:17)
  at /usr/local/lib/node_modules/truffle/truffle.es6:150:23
  at /usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:35:6
  at runTask (/usr/local/lib/node_modules/truffle/truffle.es6:55:5)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/truffle.es6:345:14)
  at Module._compile (module.js:460:26)
  at normalLoader (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6] (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/babel/lib/_babel-node.js:144:25)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by tcoulter** [comment]
Fixed. Reinstall, you should now have version 0.2.2.
