### ISSUE TITLE
Error with node-sass when running truffle init

### ISSUE THREAD

**Issue by ramvi** [ConsenSys/truffle#50]
I'm getting an error trying to run `truffle init`. I have tried the recommended fix `npm rebuild node-sass`. I have reinstalled node-sass. I have upgraded from Node 0.12 to 5.0. Still same error

```bash
$ truffle init
Error: The `libsass` binding was not found in /usr/local/lib/node_modules/truffle/node_modules/node-sass/vendor/darwin-x64-14/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
  at Object.sass.getBinaryPath (/usr/local/lib/node_modules/truffle/node_modules/node-sass/lib/extensions.js:158:11)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/node-sass/lib/index.js:16:36)
  at Module._compile (module.js:460:26)
  at Module._extensions..js (module.js:478:10)
  at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/truffle/node_modules/babel-core/lib/api/register/node.js:214:7)
  at Module.load (/usr/local/lib/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/lib/processors/scss.es6:3:12)
  at Module._compile (module.js:460:26)
  at normalLoader (/usr/local/lib/node_modules/truffle/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6] (/usr/local/lib/node_modules/truffle/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (/usr/local/lib/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.gather (/usr/local/lib/node_modules/truffle/lib/config.es6:227:38)
  at /usr/local/lib/node_modules/truffle/truffle.es6:150:23
  at /usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:35:6
  at runTask (/usr/local/lib/node_modules/truffle/truffle.es6:55:5)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/truffle.es6:347:14)
  at Module._compile (module.js:460:26)
  at normalLoader (/usr/local/lib/node_modules/truffle/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6] (/usr/local/lib/node_modules/truffle/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/babel/lib/_babel-node.js:144:25)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

**Comment by ramvi** [comment]
You know what? I had node012 linked with brew instead of version 5.0. This can be closed
