### ISSUE TITLE
Can't install via node 5.0.0 and npm 3.3.9

### ISSUE THREAD

**Issue by taoeffect** [ConsenSys/truffle#53]
```
-> % npm version
{ npm: '3.3.9',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '56.1',
  modules: '47',
  node: '5.0.0',
  openssl: '1.0.2d',
  uv: '1.7.5',
  v8: '4.6.85.28',
  zlib: '1.2.8' }
```

Tried: `npm install -g truffle`

Got:

```
npm WARN install Couldn't install optional dependency: Error extracting /Users/greg/.npm/solc/0.1.5/package.tgz archive: ENOENT: no such file or directory, open '/Users/greg/.npm/solc/0.1.5/package.tgz'
```

As a hack, symlinking `~/.npm/solc/0.1.5 -> 0.1.6-2` gets it to install.

**Comment by tcoulter** [comment]
Can you clone the truffle repository from source, and then install from there? The non-released version of Truffle has the solc version bumped to 0.1.6.

```
$ npm uninstall -g truffle
$ git clone https://github.com/ConsenSys/truffle.git
$ cd truffle
$ npm install -g .
```

Should work for you. Will release a new version soon.

**Comment by taoeffect** [comment]
That seemed to work! :smile: 

I ran EtherSim (your version) and `truffle test` on ether-crawler. Most tests passed, there was one exception at the end:

```
-> % truffle test
Using environment test.
Compiling contracts...


  Contract: Challenge
    ✓ expects character, levels, and bet (167ms)
    ✓ lets you make an offer (85ms)
    ✓ lets player accept an offer, and initializes a game (424ms)
    ✓ doesn't blow up when you claim (122ms)
    ✓ pays out royalties to levels (592ms)

  Contract: ChallengeRegistry
    ✓ should let you add a challenge (178ms)

  Contract: Game
    ✓ loads the first level (398ms)
    ✓ stores extra information about monsters (347ms)
    ✓ stores information about adventurer (277ms)
    ✓ starts the adventurer in the upper left corner (284ms)
    ✓ lets adventurer move to an empty adjacent square (302ms)
    ✓ lets adventurer consume potion (326ms)
    ✓ doesn't let adventurer move onto walls (304ms)
    ✓ doesn't let adventurer move off the edge of the world (265ms)
    1) sends adventurer to the next level if they enter a staircase
    ✓ attacks monster if adventurer tries to move onto it (354ms)
    ✓ lets player equip swords (528ms)
    ✓ kills monster when it drops below 0hp (380ms)
    ✓ levels adventurer up when they kill monster (387ms)
    ✓ moves monsters when player moves (375ms)
    ✓ attacks when player is adjacent (360ms)
    ✓ lets player equip shields (487ms)
    ✓ ends game if player goes to 0hp (381ms)
    ✓ lets you get all squares (597ms)

  Contract: Level
    ✓ should let you add a staircase (47ms)

  Contract: LevelRegistry
    ✓ should let you add a level (46ms)
    ✓ should let you get all levels at once (48ms)


  26 passing (15s)
  1 failing

  1) Contract: Game sends adventurer to the next level if they enter a staircase:
     TypeError: Cannot read property 'binary' of undefined
    at _new (node_modules/ether-pudding/build/ether-pudding.js:86:18)
    at tryCatcher (node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/main/async.js:15:14)
    at Function.module.exports.loopWhile (node_modules/deasync/index.js:64:21)
    at node_modules/deasync/index.js:36:18
    at runTask (truffle.es6:55:5)
    at Object.<anonymous> (truffle.es6:347:14)
    at normalLoader (node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .es6] (node_modules/babel-core/lib/api/register/node.js:216:7)
    at Object.<anonymous> (node_modules/babel/lib/_babel-node.js:144:25)
    at node.js:972:3
```

Not sure what to do with that.

**Comment by tcoulter** [comment]
Did you ever fix this issue?

**Comment by taoeffect** [comment]
Yep! Thank you!
