### ISSUE TITLE
/usr/local/lib/node_modules/truffle/node_modules/ether-pudding/loader.js:19

### ISSUE THREAD

**Issue by ghost** [ConsenSys/truffle#59]
root@vagrant:/home/vagrant# mkdir truffle-test
root@vagrant:/home/vagrant# cd truffle-test/
root@vagrant:/home/vagrant/truffle-test# truffle init

/usr/local/lib/node_modules/truffle/node_modules/ether-pudding/loader.js:19
      for (var file of files) {
                    ^^
SyntaxError: Unexpected identifier
  at Module._compile (module.js:439:25)
  at Module._extensions..js (module.js:474:10)
  at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
  at Module.load (/usr/local/lib/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/lib/exec.es6:9:21)
  at Module._compile (module.js:456:26)
  at normalLoader (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6] (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (/usr/local/lib/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/lib/config.es6:12:12)
  at Module._compile (module.js:456:26)
  at normalLoader (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6] (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (/usr/local/lib/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/truffle.es6:14:14)
  at Module._compile (module.js:456:26)
  at normalLoader (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6] (/usr/local/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/babel/lib/_babel-node.js:144:25)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:902:3

**Comment by ramtej** [comment]
same issues here

**Comment by reivan** [comment]
I've got around this by installing node 5.3.

**Comment by alexfisher** [comment]
Using node 5.3 got rid of this error for me, too.

**Comment by tcoulter** [comment]
Hi there. Looks like there has been a solution to this, so I'm going to close for housekeeping purposes. If you run into more trouble, don't hesitate to ask the [Truffle Gitter](https://gitter.im/ConsenSys/truffle) for help or file a new ticket. Cheers!
