### ISSUE TITLE
cannot run truffle

### ISSUE THREAD

**Issue by jimmysoa** [ConsenSys/truffle#72]
➜  ~  truffle list
/usr/local/lib/node_modules/truffle/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/truffle/node_modules/deasync/build/deasync.node
 → /usr/local/lib/node_modules/truffle/node_modules/deasync/build/Debug/deasync.node
 → /usr/local/lib/node_modules/truffle/node_modules/deasync/build/Release/deasync.node
 → /usr/local/lib/node_modules/truffle/node_modules/deasync/out/Debug/deasync.node
 → /usr/local/lib/node_modules/truffle/node_modules/deasync/Debug/deasync.node
 → /usr/local/lib/node_modules/truffle/node_modules/deasync/out/Release/deasync.node
 → /usr/local/lib/node_modules/truffle/node_modules/deasync/Release/deasync.node
 → /usr/local/lib/node_modules/truffle/node_modules/deasync/build/default/deasync.node
 → /usr/local/lib/node_modules/truffle/node_modules/deasync/compiled/5.3.0/darwin/x64/deasync.node
  at bindings (/usr/local/lib/node_modules/truffle/node_modules/bindings/bindings.js:88:9)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:23:31)
  at Module._compile (module.js:398:26)
  at Module._extensions..js (module.js:405:10)
  at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/truffle/node_modules/babel-core/lib/api/register/node.js:214:7)
  at Module.load (/usr/local/lib/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:354:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/truffle.es6:10:15)
  at Module._compile (module.js:398:26)
  at normalLoader (/usr/local/lib/node_modules/truffle/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6] (/usr/local/lib/node_modules/truffle/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (module.js:344:32)
  at Function.Module._load (module.js:301:12)
  at Function.Module.runMain (module.js:430:10)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/babel/lib/_babel-node.js:144:25)
  at Module._compile (module.js:398:26)
  at Object.Module._extensions..js (module.js:405:10)
  at Module.load (module.js:344:32)
  at Function.Module._load (module.js:301:12)
  at Function.Module.runMain (module.js:430:10)
  at startup (node.js:141:18)
  at node.js:980:3

Thanks!!!

**Comment by tcoulter** [comment]
Hmm, what's your node version? Usually deasync has a problem with old or odd node versions

**Comment by jimmysoa** [comment]
node V5.3.0 & 5.4.0 both the same error :-(

**Comment by tcoulter** [comment]
Can you install and reinstall truffle? `npm uninstall -g truffle` then `npm
install -g truffle`

**Comment by jimmysoa** [comment]
Thanks @tcoulter 

There's some WARN info  during install truffle,but the lodash version on my Mac is above 2.0.0

npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

**Comment by tcoulter** [comment]
@jimmysoa Those warnings are fine. Are you still having errors?

**Comment by jimmysoa** [comment]
I upgraded Xcode,it's ok now,Thanks.
