### ISSUE TITLE
Error: The `libsass` binding was not found in

### ISSUE THREAD

**Issue by YyItRoad** [ConsenSys/truffle#82]
promote:~ mycomputer$ truffle init
Error: The `libsass` binding was not found in /usr/local/lib/node_modules/truffle/node_modules/node-sass/vendor/darwin-x64-46/binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
  at Object.sass.getBinaryPath (/usr/local/lib/node_modules/truffle/node_modules/node-sass/lib/extensions.js:158:11)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/node-sass/lib/index.js:16:36)
  at Module._compile (module.js:435:26)
  at Module._extensions..js (module.js:442:10)
  at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/truffle/node_modules/babel-core/lib/api/register/node.js:214:7)
  at Module.load (/usr/local/lib/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/lib/processors/scss.es6:3:12)
  at Module._compile (module.js:435:26)
  at normalLoader (/usr/local/lib/node_modules/truffle/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6] (/usr/local/lib/node_modules/truffle/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (/usr/local/lib/node_modules/truffle/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:366:17)
  at require (module.js:385:17)
  at Object.gather (/usr/local/lib/node_modules/truffle/lib/config.es6:251:38)
  at /usr/local/lib/node_modules/truffle/truffle.es6:150:23
  at /usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:35:6
  at runTask (/usr/local/lib/node_modules/truffle/truffle.es6:55:5)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/truffle.es6:362:14)
  at Module._compile (module.js:435:26)
  at normalLoader (/usr/local/lib/node_modules/truffle/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6] (/usr/local/lib/node_modules/truffle/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at Object.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/babel/lib/_babel-node.js:144:25)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:136:18)
  at node.js:963:3

promote:~ mycomputer$ npm rebuild node-sass
promote:~ mycomputer$

**Comment by tcoulter** [comment]
Try `npm uninstall -g node-sass` then `npm install -g node-sass`. Do you still receive this error?

**Comment by kamil-kielczewski** [comment]
I have similar problem (blow) - but thank to @tcoulter advice now is ok :)

 Warning: Command failed: node-sass -w -r public/assets/stylesheets -o public/assets/css/dist
    /usr/local/lib/node_modules/node-sass/lib/extensions.js:158
        throw new Error([
        ^
    
    Error: The `libsass` binding was not found in /usr/local/lib/node_modules/node-sass/vendor/darwin-x64-48/binding.node
    This usually happens because your node version has changed.
    Run `npm rebuild node-sass` to build the binding for your current node version.
        at Object.sass.getBinaryPath (/usr/local/lib/node_modules/node-sass/lib/extensions.js:158:11)
        at Object.<anonymous> (/usr/local/lib/node_modules/node-sass/lib/index.js:16:36)
        at Module._compile (module.js:541:32)
        at Object.Module._extensions..js (module.js:550:10)
        at Module.load (module.js:458:32)
        at tryModuleLoad (module.js:417:12)
        at Function.Module._load (module.js:409:3)
        at Module.require (module.js:468:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/node-sass/lib/render.js:9:12)
     Use --force to continue.
    Error: Command failed: node-sass -w -r public/assets/stylesheets -o public/assets/css/dist

**Comment by tcoulter** [comment]
Hey guys. This is usually a result of a configuration issue or a problem with a specific node or npm version. I'm going close this issue as it sounds like it has been fixed. Regardless, if you're still running into trouble, don't hesitate to ask the [Truffle Gitter](https://gitter.im/ConsenSys/truffle) or file a new ticket. Thanks!
