### ISSUE TITLE
truffle installation broken - what do do?

### ISSUE THREAD

**Issue by m888m** [ConsenSys/truffle#92]
After a couple of weeks, I came back to truffle to run some tests.

I got the libsass error again, tried to uninstall / reinstall truffle, but no success.

Got many warnings telling me npm was outdated, so I went for a re-installation.
nmp would not cut it, so I decided to use nvm.
Complete uninstall, then installed both node 4.3.0 and 5.6.0 but got both time the following error:

m@888@m:~/dmc/truffle$ nvm install 4.3.0
Downloading https://nodejs.org/dist/v4.3.0/node-v4.3.0-linux-x64.tar.xz...
######################################################################## 100.0%
WARNING: checksums are currently disabled for node.js v4.0 and later
Now using node v4.3.0 (npm v2.14.12)
m@888@m:~/dmc/truffle$ npm uninstall -g truffle
npm WARN uninstall not installed in /home/m/.nvm/versions/node/v4.3.0/lib/node_modules: "truffle"
m@888@m:~/dmc/truffle$ npm install -g truffle
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
 
> deasync@0.1.4 install /home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/deasync
> node ./build.js

`linux-x64-node-4` exists; testing
Binary is fine; exiting
npm WARN optional dep failed, continuing fsevents@1.0.7
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
|
> spawn-sync@1.0.15 postinstall /home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

npm WARN deprecated lodash.padright@3.1.1: This package has been renamed. Use lodash.padend@^4.0.0.
\
> node-sass@3.4.2 install /home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/node-sass/vendor/linux-x64-46/binding.node

> node-sass@3.4.2 postinstall /home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/node-sass
> node scripts/build.js

` /home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/node-sass/vendor/linux-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
/home/m/.nvm/versions/node/v4.3.0/bin/truffle -> /home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/truffle.bash
/home/m/.nvm/versions/node/v4.3.0/bin/truffle-exec -> /home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/truffle-exec.bash
truffle@0.3.1 /home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle
├── jsmin@1.0.1
├── async@1.5.2
├── bignumber.js@2.1.4
├── ether-pudding@1.0.4
├── colors@1.1.2
├── coffee-script@1.10.0
├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
├── finalhandler@0.4.1 (escape-html@1.0.3, unpipe@1.0.0, on-finished@2.3.0, debug@2.2.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── bluebird@2.10.2
├── serve-static@1.10.2 (escape-html@1.0.3, parseurl@1.3.1, send@0.13.1)
├── node-dir@0.1.11 (minimatch@2.0.10)
├── rimraf@2.5.2 (glob@7.0.0)
├── yargs@3.32.0 (camelcase@2.1.0, window-size@0.1.4, y18n@3.2.0, decamelize@1.1.2, os-locale@1.4.0, string-width@1.0.1, cliui@3.1.0)
├── gaze@0.5.2 (globule@0.1.0)
├── chai@3.5.0 (assertion-error@1.0.1, type-detect@1.0.0, deep-eql@0.1.3)
├── cpr@0.4.3 (graceful-fs@4.1.3, rimraf@2.4.5)
├── solc@0.1.6
├── deasync@0.1.4 (bindings@1.2.1, nan@2.2.0)
├── mocha@2.4.5 (escape-string-regexp@1.0.2, commander@2.3.0, diff@1.4.0, growl@1.8.1, supports-color@1.2.0, debug@2.2.0, glob@3.2.3, jade@0.26.3)
├── uglify-js@2.6.1 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.3, yargs@3.10.0)
├── web3@0.14.0 (utf8@2.1.1, xmlhttprequest@1.8.0, bignumber.js@2.0.7, crypto-js@3.1.6)
├── lodash@3.10.1
├── babel@5.8.35 (slash@1.0.0, path-exists@1.0.0, path-is-absolute@1.0.0, fs-readdir-recursive@0.1.2, convert-source-map@1.1.3, commander@2.9.0, output-file-sync@1.1.1, source-map@0.5.3, glob@5.0.15, chokidar@1.4.2, babel-core@5.8.35)
└── node-sass@3.4.2 (get-stdin@4.0.1, async-foreach@0.1.3, chalk@1.1.1, nan@2.2.0, glob@5.0.15, npmconf@2.1.2, meow@3.7.0, cross-spawn@2.1.5, request@2.69.0, sass-graph@2.1.1, node-gyp@3.2.1)
m@888@m:~/dmc/truffle$ truffle deploy
Using environment development.
Error: Invalid JSON RPC response: "Error: connect ECONNREFUSED 127.0.0.1:8545\n  at Object.exports._errnoException (util.js:870:11)\n  at exports._exceptionWithHostPort (util.js:893:20)\n  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)\n  at Function.module.exports.loopWhile (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/deasync/index.js:64:21)\n  at /home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/deasync/index.js:36:18\n  at runTask (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/truffle.es6:55:5)\n  at Object.<anonymous> (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/truffle.es6:362:14)\n  at Module._compile (module.js:410:26)\n  at normalLoader (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)\n  at Object.require.extensions.(anonymous function) [as .es6] (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)\n  at Module.load (module.js:344:32)\n  at Function.Module._load (module.js:301:12)\n  at Function.Module.runMain (module.js:442:10)\n  at Object.<anonymous> (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/babel/lib/_babel-node.js:144:25)\n  at Module._compile (module.js:410:26)\n  at Object.Module._extensions..js (module.js:417:10)\n  at Module.load (module.js:344:32)\n  at Function.Module._load (module.js:301:12)\n  at Function.Module.runMain (module.js:442:10)\n  at startup (node.js:136:18)\n  at node.js:966:3\n"
  at Object.module.exports.InvalidResponse (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/web3/lib/web3/errors.js:35:16)
  at [object Object].request.onreadystatechange (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:111:32)
  at [object Object].dispatchEvent (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/web3/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
  at setState (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/web3/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
  at [object Object].handleError (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/web3/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:532:5)
  at ClientRequest.errorHandler (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/web3/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
  at emitOne (events.js:77:13)
  at ClientRequest.emit (events.js:169:7)
  at Socket.socketErrorListener (_http_client.js:258:9)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at emitErrorNT (net.js:1256:8)
  at nextTickCallbackWith2Args (node.js:441:9)
  at process._tickDomainCallback (node.js:396:17)
  at Function.module.exports.loopWhile (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/deasync/index.js:64:21)
  at /home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/deasync/index.js:36:18
  at runTask (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/truffle.es6:55:5)
  at Object.<anonymous> (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/truffle.es6:362:14)
  at Module._compile (module.js:410:26)
  at normalLoader (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
  at Object.require.extensions.(anonymous function) [as .es6] (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
  at Module.load (module.js:344:32)
  at Function.Module._load (module.js:301:12)
  at Function.Module.runMain (module.js:442:10)
  at Object.<anonymous> (/home/m/.nvm/versions/node/v4.3.0/lib/node_modules/truffle/node_modules/babel/lib/_babel-node.js:144:25)
  at Module._compile (module.js:410:26)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load (module.js:344:32)
  at Function.Module._load (module.js:301:12)
  at Function.Module.runMain (module.js:442:10)
  at startup (node.js:136:18)
  at node.js:966:3

**Comment by jonnor** [comment]
@m888m are you running `testrpc`, `geth --rpc` or some other Ethereum client with RPC enabled?
`Error: Invalid JSON RPC response: "Error: connect ECONNREFUSED 127.0.0.1:8545\` suggests it is having trouble connecting to that

**Comment by tcoulter** [comment]
I'm going to close this for housekeeping purposes. If you continue to have this error please reopen.

**Comment by animesh21** [comment]
You need to run testrpc in a separate terminal window or run as a background process in order to connect to it. Run this command in another terminal:
`username@workstation$ testrpc -a`
and minimize it and then do whatever you were doing.
