### ISSUE TITLE
web3 is not in the global scope of the console

### ISSUE THREAD

**Issue by jellegerbrandy** [ConsenSys/truffle#97]
```
truffle(development)> web3
ReferenceError: web3 is not defined
    at repl:1:1
    at REPLServer.defaultEval (repl.js:254:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:90:13)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
truffle(development)> 
```
I am aware that #58 addressed a similar issue (but also talked about availability of web3 in tests), but that fix has apparently not resolved the problem.

**Comment by tcoulter** [comment]
Fixed on master. Cheers!
